### ISSUE TITLE
Library not mentioned

### ISSUE THREAD

**Issue by joelcnz** [Flying-Toast/wiziz#87]
ld: library not found for -lssl

What library do I install for that? I use macOS (Mojave) and home brew.

**Comment by Flying-Toast** [comment]
Maybe  `brew install openssl`? If that doesn't work, adding a line to dub.sdl with `versions "VibeNoSSL"` should solve it.

**Comment by joelcnz** [comment]
Ok, thanks. Installing openssl worked.
